// Copyright (c) 2026, Salesforce, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Pre-execution phase statistics (parsing and compilation). */
export interface JsPreExecutionStats {
  /** Time spent parsing the SQL (seconds). */
  parsingTimeS?: number
  /** Time spent compiling the query plan (seconds). */
  compilationTimeS?: number
  /** Total pre-execution elapsed time (seconds). */
  elapsedS?: number
  /** Peak transaction memory during pre-execution (MB). */
  peakMemoryMb?: number
}
/** Execution phase statistics (runtime performance). */
export interface JsExecutionStats {
  /** Total execution elapsed time (seconds). */
  elapsedS?: number
  /** CPU time consumed (seconds). */
  cpuTimeS?: number
  /** Total thread time (seconds). */
  threadTimeS?: number
  /** Time spent waiting (seconds). */
  waitTimeS?: number
  /** Total rows processed. */
  processedRowsTotal?: number
  /** Rows processed from native storage. */
  processedRowsNative?: number
  /** Time spent on storage access (seconds). */
  storageAccessTimeS?: number
  /** Number of storage access operations. */
  storageAccessCount?: number
  /** Bytes read from storage. */
  storageAccessBytes?: number
  /** Peak transaction memory during execution (MB). */
  peakMemoryMb?: number
}
/** Detailed statistics for a single query execution. */
export interface JsQueryStats {
  /** Total elapsed wall-clock time (seconds). */
  elapsedS: number
  /** Time spent committing (seconds). */
  commitTimeS?: number
  /** Time waiting to be scheduled (seconds). */
  timeToScheduleS?: number
  /** Pre-execution phase stats. */
  preExecution?: JsPreExecutionStats
  /** Execution phase stats. */
  execution?: JsExecutionStats
  /** Result size (MB). */
  resultSizeMb?: number
  /** Peak result buffer memory (MB). */
  peakResultBufferMemoryMb?: number
  /** Plan cache status. */
  planCacheStatus?: string
  /** Plan cache hit count. */
  planCacheHitCount?: number
  /** Statement type. */
  statementType?: string
  /** Result row count. */
  rows?: number
  /** Result column count. */
  cols?: number
  /** Truncated query text from Hyper log. */
  queryTruncated?: string
}
/** Metadata about a column in a query result. */
export interface ResultColumnInfo {
  /** Column name. */
  name: string
  /** SQL type name. */
  typeName: string
  /** Column index (0-based). */
  index: number
}
/** How to handle database creation when connecting. */
export const enum CreateMode {
  /** Do not create the database (it must already exist). */
  DoNotCreate = 'DoNotCreate',
  /** Create the database (fails if it already exists). */
  Create = 'Create',
  /** Create the database if it doesn't exist. */
  CreateIfNotExists = 'CreateIfNotExists',
  /** Drop and recreate the database. */
  CreateAndReplace = 'CreateAndReplace'
}
/**
 * TLS settings for `ConnectionBuilder.tls()`, with libpq `sslmode`
 * semantics.
 */
export interface TlsOptions {
  /** `"disable"`, `"prefer"`, `"require"`, `"verify-ca"` or `"verify-full"`. */
  mode: string
  /**
   * PEM file of trusted root certificates. Required by `"verify-ca"` and
   * `"verify-full"`; with `"prefer"` or `"require"` it turns on chain
   * verification.
   */
  rootCert?: string
  /** PEM client certificate for mutual TLS. Requires `clientKey`. */
  clientCert?: string
  /** PEM private key for `clientCert`. */
  clientKey?: string
  /** Host name to verify and send as SNI instead of the endpoint's host. */
  serverName?: string
}
/** Options for starting a `HyperProcess`. */
export interface HyperProcessOptions {
  /**
   * `"tcp"` (the default) or `"ipc"`: a Unix domain socket, or a named
   * pipe on Windows. TLS needs `"tcp"`.
   */
  transport?: string
  /**
   * `hyperd` settings, passed through unchanged, for example `ssl_key`
   * and `ssl_certificate` to serve TLS.
   */
  parameters?: Record<string, string>
}
/** Information about a single column in a table definition. */
export interface ColumnInfo {
  /** Column name. */
  name: string
  /** SQL type name (e.g., "INTEGER", "TEXT"). */
  typeName: string
  /** Whether the column allows NULL values. */
  nullable: boolean
}
/**
 * Arrow-native bulk inserter.
 *
 * Accepts a raw Arrow IPC stream (the byte buffer produced by
 * `apache-arrow`'s `RecordBatchStreamWriter` / `Table.serialize()`) and
 * streams it straight into Hyper via the async COPY path. There is no
 * per-row JS→Rust conversion — this is the fastest way to bulk-load
 * tabular data from a Node.js process that already has Arrow batches
 * in hand.
 *
 * @example
 * ```js
 * import { tableFromArrays } from 'apache-arrow';
 *
 * const table = tableFromArrays({
 *   id: Int32Array.from([1, 2, 3]),
 *   value: Float64Array.from([1.5, 2.5, 3.5]),
 * });
 *
 * const inserter = await ArrowInserter.create(conn, tableDef);
 * await inserter.insertRaw(Buffer.from(table.serialize()));
 * const rowCount = await inserter.execute();
 * ```
 */
export declare class ArrowInserter {
  /** Creates a new ArrowInserter bound to the given connection and table. */
  static create(connection: Connection, tableDef: TableDefinition): ArrowInserter
  /**
   * Sends a chunk of Arrow IPC stream bytes to the server.
   *
   * Accepts the raw byte buffer produced by `apache-arrow`'s
   * `RecordBatchStreamWriter` — schema on the first call, record
   * batches on subsequent calls, or a complete IPC stream in one
   * shot.
   */
  insertRaw(buf: Buffer): Promise<void>
  /**
   * Finalizes the COPY stream and returns the number of rows inserted.
   *
   * After this call, the inserter cannot be reused.
   */
  execute(): Promise<number>
  /** Cancels the COPY stream without committing any rows. */
  cancel(): Promise<void>
  /** True until any data has been sent; useful for conditional flushes. */
  hasData(): Promise<boolean>
  /** Total bytes sent to the server so far. */
  totalBytes(): Promise<number>
  /** Number of Arrow IPC chunks sent so far. */
  chunkCount(): Promise<number>
}
/**
 * Provides database catalog operations (DDL): create/drop tables, schemas, etc.
 *
 * A Catalog operates on the connection it was created from.
 *
 * @example
 * ```js
 * const catalog = new Catalog(conn);
 * await catalog.createSchema('my_schema');
 * await catalog.createTable(tableDef);
 * const tables = await catalog.getTableNames('public');
 * ```
 */
export declare class Catalog {
  /** Creates a new Catalog for the given connection. */
  constructor(connection: Connection)
  /** Creates a schema if it does not already exist. */
  createSchema(schemaName: string): Promise<void>
  /** Creates a table from a TableDefinition. */
  createTable(tableDef: TableDefinition): Promise<void>
  /** Creates a table if it doesn't already exist. */
  createTableIfNotExists(tableDef: TableDefinition): Promise<void>
  /** Drops a table. */
  dropTable(tableName: string): Promise<void>
  /** Drops a table if it exists (no error if missing). */
  dropTableIfExists(tableName: string): Promise<void>
  /** Drops a schema. Pass `cascade = true` to drop all objects in the schema. */
  dropSchema(schemaName: string, cascade: boolean): Promise<void>
  /** Checks whether a schema exists. */
  hasSchema(schemaName: string): Promise<boolean>
  /**
   * Checks whether a table exists.
   *
   * @param tableName - "table" or "schema.table".
   */
  hasTable(tableName: string): Promise<boolean>
  /** Returns a list of table names in the given schema. */
  getTableNames(schemaName: string): Promise<Array<string>>
  /** Returns a list of schema names in the database. */
  getSchemaNames(): Promise<Array<string>>
}
/**
 * A chunk of query results stored in columnar format for high-performance access.
 *
 * Instead of per-row, per-cell accessor calls, columnar chunks let you retrieve
 * an entire column at once as a flat array. This reduces JS↔Rust FFI overhead
 * from O(rows × columns) to O(columns).
 *
 * @example
 * ```js
 * const stream = conn.executeQueryColumnar('SELECT id, value FROM t');
 * let chunk;
 * while ((chunk = await stream.nextChunk()) !== null) {
 *   const ids = chunk.getInt32Column(0);       // number[]
 *   const values = chunk.getFloat64Column(1);  // number[]
 *   const nulls = chunk.getNulls(1);           // boolean[]
 *   // Process arrays in bulk — no per-row FFI!
 * }
 * ```
 */
export declare class ColumnarChunk {
  /** Number of rows in this chunk. */
  get rowCount(): number
  /** Number of columns. */
  get columnCount(): number
  /**
   * Returns an entire column as an array of 32-bit integers.
   *
   * Null values are represented as 0. Use `getNulls(index)` to distinguish nulls.
   *
   * Float64 columns are coerced by saturating: out-of-range values clamp to
   * the Int32 bounds and `NaN` becomes 0.
   *
   * @throws If the column is Int64 and any value does not fit an Int32.
   * Truncating would yield a plausible-looking wrong number, so this rejects
   * instead. Use `getInt64Column(index)` to widen instead of narrow — noting
   * that it returns `number`, which itself loses precision above 2^53.
   */
  getInt32Column(index: number): Array<number>
  /**
   * Returns an entire column as an array of 64-bit floats.
   *
   * Null values are represented as 0.0. Use `getNulls(index)` to distinguish nulls.
   */
  getFloat64Column(index: number): Array<number>
  /**
   * Returns an entire column as an array of 64-bit integers (as JS numbers).
   *
   * Note: JS numbers lose precision above 2^53.
   * Null values are represented as 0. Use `getNulls(index)` to distinguish nulls.
   */
  getInt64Column(index: number): Array<number>
  /** Returns an entire column as an array of strings. */
  getStringColumn(index: number): Array<string>
  /**
   * Returns a boolean array indicating which rows are null for the given column.
   *
   * `true` means the value is null.
   */
  getNulls(index: number): Array<boolean>
}
/**
 * A streaming query result that returns columnar chunks for high-performance bulk access.
 *
 * Each chunk contains typed arrays per column instead of per-row objects,
 * reducing FFI overhead from O(rows × columns) to O(columns).
 *
 * @example
 * ```js
 * const stream = conn.executeQueryColumnar('SELECT id, value FROM measurements');
 * let chunk;
 * while ((chunk = await stream.nextChunk()) !== null) {
 *   const ids = chunk.getInt32Column(0);
 *   const values = chunk.getFloat64Column(1);
 *   // Process in bulk...
 * }
 * ```
 */
export declare class ColumnarStream {
  /** Returns the next columnar chunk, or `null` when all rows have been consumed. */
  nextChunk(): Promise<ColumnarChunk | null>
  /** Returns column metadata for this result set. */
  getSchema(): Array<ResultColumnInfo> | null
}
/**
 * An async connection to a Hyper database.
 *
 * All I/O methods return Promises — use `await` when calling them. The
 * binding is backed by [`hyperapi::AsyncConnection`], so concurrent
 * calls share a single tokio task pool rather than each burning a
 * thread on the napi blocking pool.
 */
export declare class Connection {
  /** Connects to a Hyper server with a database. */
  static connect(endpoint: string, databasePath: string, createMode: CreateMode): Promise<Connection>
  /** Connects with username and password authentication. */
  static connectWithAuth(endpoint: string, databasePath: string, createMode: CreateMode, user: string, password: string): Promise<Connection>
  /** Connects to a Hyper server without attaching a database. */
  static withoutDatabase(endpoint: string): Promise<Connection>
  /** Executes a SQL command that doesn't return rows (CREATE, INSERT, DROP, etc.). */
  executeCommand(sql: string): Promise<number>
  /**
   * Executes a SQL query and returns all result rows.
   *
   * All rows are collected into memory. Use `executeQueryStream` for very
   * large result sets.
   */
  executeQuery(sql: string): Promise<Array<RowData>>
  /** Executes a query and returns column metadata for the result set. */
  querySchema(sql: string): Promise<Array<ResultColumnInfo>>
  /** Executes a SQL query and returns a streaming result set. */
  executeQueryStream(sql: string): QueryStream
  /** Executes a SQL query and returns a columnar streaming result set. */
  executeQueryColumnar(sql: string): ColumnarStream
  /** Executes a SQL query and returns the result as raw Arrow IPC stream bytes. */
  executeQueryToArrow(sql: string): Promise<Buffer>
  /** Exports an entire table as raw Arrow IPC stream bytes. */
  exportTableToArrow(tableName: string): Promise<Buffer>
  /** Returns the database path, if a database is attached. */
  get database(): string | null
  /** Returns true if the connection is alive. */
  get isAlive(): boolean
  /**
   * Returns true if the session is encrypted with TLS.
   *
   * `false` for a plaintext TCP connection, including a
   * `{ mode: 'prefer' }` connection whose server declined TLS, and for a
   * Unix domain socket or named pipe.
   */
  get isTls(): boolean
  /**
   * Closes the connection.
   *
   * After calling this, no further operations should be performed on this
   * connection. The underlying `AsyncConnection` is released when the
   * last Arc-clone is dropped; calling `close` eagerly runs the
   * detach-database handshake.
   */
  close(): Promise<void>
  /** Enables query statistics collection by parsing Hyper's log file. */
  enableQueryStats(logPath: string): void
  /** Disables query statistics collection. */
  disableQueryStats(): void
  /** Returns the query statistics from the most recent query execution. */
  lastQueryStats(): JsQueryStats | null
  /**
   * Prepares a SQL statement for parameterized execution.
   *
   * Parameter types are inferred from the JS values passed on the
   * first call; if those types change between calls the statement
   * re-prepares transparently. For explicit OID control, use
   * [`prepareTyped`](Self::prepare_typed).
   */
  prepare(sql: string): PreparedStatement
  /**
   * Prepares a SQL statement with explicit parameter type OIDs.
   *
   * Use this when the inferred types are ambiguous or when you want
   * to pin the server-side plan cache entry.
   */
  prepareTyped(sql: string, paramOids: Array<number>): Promise<PreparedStatement>
  /**
   * Tagged template for parameterized queries. Rewrites `${value}` placeholders
   * to `$1`, `$2`, ... and runs through a prepared statement. Returns rows
   * with index-based accessors (`row.getInt32(0)`, etc.) — for typed plain
   * objects, use {@link Connection.sqlTyped} or {@link Connection.queryObjects}.
   *
   * @example
   * ```js
   * const rows = await conn.sql`SELECT * FROM users WHERE id = ${id}`
   * ```
   */
  sql(strings: TemplateStringsArray, ...values: Array<number | bigint | string | boolean | null | Date>): Promise<Array<RowData>>
  /**
   * Like {@link Connection.sql} but returns typed plain objects instead of
   * `RowData`. Column values are returned as strings (text representation).
   *
   * The generic parameter `T` is asserted, not enforced — TypeScript trusts
   * that the SQL columns match the shape of `T`. There is no schema check at
   * compile time. For full schema-driven inference, use a Drizzle / Kysely
   * driver adapter instead.
   *
   * @example
   * ```ts
   * type UserRow = { id: string; name: string };
   * const rows = await conn.sqlTyped<UserRow>`SELECT id, name FROM users`
   * ```
   */
  sqlTyped<T = Record<string, string | null>>(
    strings: TemplateStringsArray,
    ...values: Array<number | bigint | string | boolean | null | Date>
  ): Promise<Array<T>>
  /**
   * Tagged template for parameterized DML commands. Rewrites `${value}` placeholders
   * to `$1`, `$2`, ... and runs through a prepared statement. Returns affected row count.
   */
  command(strings: TemplateStringsArray, ...values: Array<number | bigint | string | boolean | null | Date>): Promise<number>
  /**
   * Runs `fn` inside a transaction. Issues `BEGIN`, then the callback, then
   * `COMMIT` on success or `ROLLBACK` on error.
   */
  transaction<T>(fn: (conn: Connection) => Promise<T>): Promise<T>
  /**
   * Executes a query and returns rows as plain JS objects with column names
   * as keys. All values are returned as strings (text representation).
   *
   * The generic parameter `T` is asserted, not enforced — TypeScript trusts
   * that the SQL columns match the shape of `T`. For full schema-driven
   * inference, use a Drizzle / Kysely driver adapter instead.
   */
  queryObjects<T = Record<string, string | null>>(sql: string): Promise<Array<T>>
  /** Disposable cleanup hook used by `await using conn = ...`. Calls close(). */
  [Symbol.asyncDispose](): Promise<void>
}
/** A fluent builder for creating connections with advanced options. */
export declare class ConnectionBuilder {
  /** Creates a new ConnectionBuilder for the given endpoint. */
  constructor(endpoint: string)
  /** Sets the database path. */
  database(path: string): this
  /** Sets the database creation mode. */
  createMode(mode: CreateMode): this
  /** Sets the username for authentication. */
  user(user: string): this
  /** Sets the password for authentication. */
  password(password: string): this
  /** Sets the login timeout in milliseconds. */
  loginTimeout(ms: number): this
  /**
   * Sets the TLS options for a TCP connection; the default is
   * `{ mode: 'disable' }`.
   *
   * Over a Unix domain socket or a named pipe, `"prefer"` connects in
   * plaintext and the modes that require TLS fail `build()`. A gRPC
   * endpoint picks TLS through its `https://` scheme, so any mode but
   * `"disable"` fails there too. The options are checked by `build()`.
   */
  tls(options: TlsOptions): this
  /** Builds and establishes the connection. */
  build(): Promise<Connection>
}
/**
 * Row-at-a-time bulk inserter backed by HyperBinary COPY.
 *
 * Rows are buffered in memory; `execute()` encodes them into Hyper's
 * binary COPY format and ships them to the server on a tokio task.
 * For Arrow IPC data, use [`ArrowInserter`](crate::arrow_inserter::ArrowInserter)
 * instead — it bypasses the per-row JS encoding loop entirely.
 */
export declare class RowInserter {
  /** Creates a new RowInserter for the given connection and table definition. */
  constructor(connection: Connection, tableDef: TableDefinition)
  /** Adds a row of values to the insert buffer. */
  addRow(values: Array<number | string | boolean | null | Buffer>): void
  /** Adds multiple rows at once. */
  addRows(rows: Array<Array<number | string | boolean | null | Buffer>>): void
  /** Returns the number of buffered rows. */
  get bufferedRowCount(): number
  /**
   * Adds rows from columnar (per-column) typed arrays.
   *
   * Significantly faster than `addRows()` for numeric data — avoids
   * per-cell JS type detection.
   */
  addColumnar(int32Columns: Record<number, number[]>, float64Columns: Record<number, number[]>, int64Columns: Record<number, number[]>, rowCount: number): void
  /**
   * Sends all buffered rows to the server and returns the number of rows inserted.
   *
   * HyperBinary encoding is CPU-bound; we run it on tokio's blocking
   * pool so the event loop stays free for other requests. The actual
   * socket I/O after encoding runs on the async pool.
   */
  execute(): Promise<number>
}
/**
 * A server-side prepared statement bound to a [`Connection`].
 *
 * Prepared statements are the supported way to run parameterized
 * queries: parameter values are sent over the wire in native binary
 * format — no per-value string escaping, no SQL-injection surface.
 *
 * ## Type inference
 *
 * [`Connection.prepare(sql)`] defers server-side preparation until the
 * first call to `query`/`execute` because Hyper's Parse message
 * requires the exact set of parameter OIDs up front. The first call
 * prepares using the OIDs inferred from the JS parameter values, then
 * caches the prepared statement for subsequent calls.
 *
 * If you later call `query` with *different* types for the same
 * placeholders (e.g. `[42]` then `[42n]`), the statement re-prepares
 * transparently. For predictable, cache-hot behavior pass explicit
 * OIDs via [`Connection.prepareTyped(sql, oids)`].
 *
 * @example
 * ```js
 * const stmt = await conn.prepare('SELECT * FROM users WHERE id = $1');
 * const rows = await stmt.query([42]);
 * const count = await stmt.execute([42]);
 * await stmt.close();
 * ```
 */
export declare class PreparedStatement {
  /** Number of parameters this statement expects. */
  get paramCount(): number
  /** Original SQL text. */
  get sql(): string
  /** Executes the statement and returns every row. */
  query(params: Array<number | bigint | string | boolean | null | Buffer>): Promise<Array<RowData>>
  /**
   * Executes the statement as a command (INSERT/UPDATE/DELETE) and
   * returns the number of affected rows.
   */
  execute(params: Array<number | bigint | string | boolean | null | Buffer>): Promise<number>
  /** Fetches exactly one row; errors if the result is empty. */
  fetchOne(params: Array<number | bigint | string | boolean | null | Buffer>): Promise<RowData>
  /** Fetches at most one row; returns `null` if the result is empty. */
  fetchOptional(params: Array<number | bigint | string | boolean | null | Buffer>): Promise<RowData | null>
  /**
   * Returns the result-set schema (column metadata) for this prepared
   * statement. Returns `null` if the statement has not been prepared on the
   * server yet (no `query`/`execute` call has run).
   */
  getSchema(): Promise<Array<ResultColumnInfo> | null>
  /** Explicitly releases the statement on the server. */
  close(): Promise<void>
}
/**
 * Manages a local Hyper server process.
 *
 * The server is automatically started when a `HyperProcess` is created and
 * stopped when `close()` is called. You **must** call `close()` when done
 * to ensure the server process is properly terminated.
 *
 * @example
 * ```js
 * const hyper = new HyperProcess();
 * const conn = await hyper.connectToDatabase('test.hyper', CreateMode.CreateIfNotExists);
 * // ... use the connection ...
 * await conn.close();
 * hyper.close();
 * ```
 */
export declare class HyperProcess {
  /**
   * Creates and starts a new Hyper server process.
   *
   * The server binary (`hyperd`) is automatically located. Pass a custom
   * path if it's not in the standard location.
   *
   * @param hyperPath - Optional path to the `hyperd` binary.
   * @param options - Optional transport and `hyperd` settings.
   */
  constructor(hyperPath?: string | undefined | null, options?: HyperProcessOptions | undefined | null)
  /**
   * Returns the server endpoint: `host:port` (e.g., "127.0.0.1:7483"),
   * or with `transport: 'ipc'` the Unix socket path or named pipe.
   *
   * Use this to connect to the server via `Connection.connect()`.
   */
  get endpoint(): string
  /**
   * Convenience method: connects to this server with a database.
   *
   * @param databasePath - Path to the database file.
   * @param createMode - How to handle database creation.
   */
  connectToDatabase(databasePath: string, createMode: CreateMode): Promise<Connection>
  /**
   * Stops the Hyper server process.
   *
   * This must be called when you're done to ensure proper cleanup.
   * After calling this, no further connections can be made.
   */
  close(): void
  /** Returns true if the process is still running. */
  get isOpen(): boolean
  /**
   * Returns the path to the Hyper log file (`hyperd.log`).
   *
   * Use this with `conn.enableQueryStats(hyper.logPath)` to enable
   * detailed query performance statistics collection.
   *
   * Returns `null` if the log directory could not be determined.
   */
  get logPath(): string | null
}
/**
 * A streaming query result for memory-efficient iteration over large result sets.
 *
 * Rows are fetched in chunks on demand — only one chunk is buffered at a time.
 *
 * ## Chunk-level iteration (high performance)
 *
 * ```js
 * const stream = await conn.executeQueryStream('SELECT * FROM big_table');
 * let chunk;
 * while ((chunk = await stream.nextChunk()) !== null) {
 *   for (const row of chunk) {
 *     console.log(row.getInt32(0));
 *   }
 * }
 * ```
 *
 * ## Row-level async iteration (convenient)
 *
 * ```js
 * const stream = await conn.executeQueryStream('SELECT * FROM big_table');
 * for await (const row of stream) {
 *   console.log(row.getInt32(0));
 * }
 * ```
 */
export declare class QueryStream {
  /** Returns the next chunk of rows, or `null` when all rows have been consumed. */
  nextChunk(): Promise<Array<RowData> | null>
  /** Returns column metadata for this result set (populated after the first chunk). */
  getSchema(): Array<ResultColumnInfo> | null
}
/**
 * A row from a query result.
 *
 * Use the typed accessor methods to get column values by index (0-based).
 * Returns `null` for NULL values or type mismatches.
 */
export declare class RowData {
  /** Returns the number of columns in this row. */
  get columnCount(): number
  /** Returns true if the value at the given column index is NULL. */
  isNull(index: number): boolean
  /** Gets a boolean value at the given column index. */
  getBool(index: number): boolean | null
  /**
   * Gets a 32-bit integer value at the given column index.
   *
   * Float and Numeric cells are coerced by saturating: out-of-range values
   * clamp to the Int32 bounds and `NaN` becomes 0. Use `getFloat64(index)` for
   * the unrounded value.
   *
   * @throws If the cell holds a BIGINT outside the range of an Int32.
   * Truncating would return a plausible-looking wrong number, and returning
   * `null` would be indistinguishable from a SQL NULL. Use
   * `getBigInt(index)` for lossless access.
   */
  getInt32(index: number): number | null
  /**
   * Gets a 64-bit integer value at the given column index.
   * Note: JavaScript numbers lose precision above 2^53. For very large
   * integers, use `getBigInt()` instead.
   */
  getInt64(index: number): number | null
  /**
   * Gets a Date value as a Unix timestamp in milliseconds.
   *
   * Pass the result to `new Date(ms)` in JS to get a Date object.
   * Returns `null` for non-date columns or NULL values.
   */
  getDateMs(index: number): number | null
  /**
   * Gets a Timestamp value as a Unix timestamp in milliseconds.
   *
   * Pass the result to `new Date(ms)` in JS to get a Date object.
   * Works for both TIMESTAMP and TIMESTAMP WITH TIME ZONE columns.
   */
  getTimestampMs(index: number): number | null
  /**
   * Gets a JSON column value as a parsed string (ready for JSON.parse in JS).
   *
   * Returns the raw JSON text. Use `JSON.parse(row.getJSON(idx))` in JS.
   */
  getJson(index: number): string | null
  /**
   * Gets a 64-bit integer as a BigInt (no precision loss).
   *
   * Unlike `getInt64()` which returns a JS `number` (lossy above 2^53),
   * this returns a native `BigInt`.
   */
  getBigInt(index: number): bigint | null
  /** Gets a double-precision float value at the given column index. */
  getFloat64(index: number): number | null
  /**
   * Gets a string value at the given column index.
   * Non-string types are converted to their string representation.
   */
  getString(index: number): string | null
  /** Gets raw bytes (Buffer) at the given column index. */
  getBytes(index: number): Buffer | null
}
/**
 * Represents a SQL column type.
 *
 * Use the static factory methods to create instances:
 * `SqlType.int()`, `SqlType.text()`, `SqlType.bool()`, etc.
 */
export declare class SqlType {
  /** Boolean type. */
  static bool(): SqlType
  /** 16-bit integer (SMALLINT). */
  static smallInt(): SqlType
  /** 32-bit integer (INT). */
  static int(): SqlType
  /** 64-bit integer (BIGINT). */
  static bigInt(): SqlType
  /** Single-precision floating point (REAL). */
  static float(): SqlType
  /** Double-precision floating point (DOUBLE PRECISION). */
  static double(): SqlType
  /** Numeric/decimal type with precision and scale. */
  static numeric(precision: number, scale: number): SqlType
  /** Variable-length text (TEXT). */
  static text(): SqlType
  /** Variable-length character string with optional max length (VARCHAR). */
  static varchar(maxLength?: number | undefined | null): SqlType
  /** Fixed-length character string (CHAR). */
  static char(length: number): SqlType
  /** Binary data (BYTEA). */
  static bytes(): SqlType
  /** Date type. */
  static date(): SqlType
  /** Time type. */
  static time(): SqlType
  /** Timestamp without timezone. */
  static timestamp(): SqlType
  /** Timestamp with timezone. */
  static timestampTz(): SqlType
  /** Time interval. */
  static interval(): SqlType
  /** JSON type. */
  static json(): SqlType
  /** Geography type. */
  static geography(): SqlType
  /** Returns the SQL type name (e.g., "INTEGER", "TEXT", "NUMERIC(18, 2)"). */
  toString(): string
}
/**
 * Defines the schema of a database table.
 *
 * Use this to create tables via `Catalog.createTable()` or for bulk inserts
 * via `Inserter`.
 */
export declare class TableDefinition {
  /** Creates a new table definition with the given name. */
  constructor(name: string)
  /** Sets the schema name and returns the definition for chaining. */
  withSchema(schema: string): this
  /**
   * Adds a column to the table definition.
   *
   * @param name - Column name.
   * @param sqlType - The SQL type for this column.
   * @param nullable - Whether the column allows NULL values.
   */
  addColumn(name: string, sqlType: SqlType, nullable: boolean): this
  /** Returns the number of columns. */
  get columnCount(): number
  /** Returns the table name. */
  get name(): string
  /** Returns the schema name, if set. */
  get schema(): string | null
  /** Returns column information as an array of objects. */
  getColumns(): Array<ColumnInfo>
  /** Generates the CREATE TABLE SQL statement. */
  toCreateSql(): string
}

/**
 * Returns the absolute path to the bundled `hyperd` binary, or `null` if not found.
 * Checks `HYPERD_PATH` env var first, then the installed platform package.
 */
export function getHyperdPath(): string | null
